### ISSUE TITLE
Abandoned project?

### ISSUE THREAD

**Issue by MartinCarpentier** [GeoJSON-Net/GeoJSON.Text#13]
Hey @matt-lethargic 

Have you abandoned the project? 

Seems like there's little to no traction for the last month, which i sad, since i personally feel like this library could be a real improvement.

**Comment by matt-lethargic** [comment]
I don't want it to be abandoned, but with work and life I'm struggling to find time ☹️

**Comment by MartinCarpentier** [comment]
If you want, i can get the project to release version 1.0.0, but i don't have enough privileges over this repository right now.

**Comment by matt-lethargic** [comment]
You should now have admin rights for this repo :-)
