### ISSUE TITLE
Publish newer versions to NuGet

### ISSUE THREAD

**Issue by M1sterPl0w** [GeoJSON-Net/GeoJSON.Text#28]
Hi, 

I noticed that recent updates haven’t been pushed to NuGet in a while. When I attempted to install the latest version, it tried to pull in System.Text.Json 6.0.1 rather than the 8.0.5 version currently used in this project.

Would it be possible for one of the contributors to update the package on NuGet? If needed, I’d be glad to assist with this process.

Kind regards,

Jeroen

**Comment by janusw** [comment]
While there is no updated version on nuget yet, there is one thing that you can do as a workaround (if you depend on it really urgently): Download the nupkg generated by GHA for the current main branch from https://github.com/GeoJSON-Net/GeoJSON.Text/actions/runs/11608790846#artifacts, save it locally and use a local package source to include it in your project.

But you are right: The last public release 1.0.2 on nuget.org is more than a year old, and several fixes have been applies on the main branch by now. One should tag a new version (1.0.3 or 1.1.0?) and upload it to nuget.org (the latter can only be done by @xfischer or @matt-lethargic).

**Comment by M1sterPl0w** [comment]
@janusw  Thanks for you reaction!

That will not work for me. But that's okay. I hope the people you mentioned will release the official way :)

**Comment by xfischer** [comment]
Yes I’ll do it tonight. Sorry for the poor availability lately.

**Comment by janusw** [comment]
> Yes I’ll do it tonight.

If you do, it might be a good idea to also update the version in the csproj, which is currently "0.1.0":

https://github.com/GeoJSON-Net/GeoJSON.Text/blob/2f669b361e877b74d01dc9e5281f3cd821f2e7d9/src/GeoJSON.Text/GeoJSON.Text.csproj#L11

**Comment by xfischer** [comment]
1.1.0 published ! https://www.nuget.org/packages/GeoJSON.Text/1.1.0

**Comment by M1sterPl0w** [comment]
@xfischer you are amazing! Thanks!

**Comment by xfischer** [comment]
You both did the heavylifting, thanks again !
